{/* possible collections
machinedBadges
bullionCrests
braiding
arras
aiguillette

*/}
const products = [
    {
      id: "1",
      name: "Paris",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 19.99,
      image: "/1.jpg",
      collection: "bullionCrests",
    },
    {
      id: "2",
      name: "Carleton University",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 29.99,
      image: "/2.jpg",
      collection: "bullionCrests",
    },
    {
      id: "3",
      name: "Ontario",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/3.jpg",
      collection: "machinedBadges",
    },
    {
      id: "4",
      name: "Toronto Police",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/4.jpg",
      collection: "machinedBadges",
    },
    {
      id: "5",
      name: "Ontario Legion",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/5.jpg",
      collection: "bullionCrests",
    },
    {
      id: "6",
      name: "Mountee",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/6.jpg",
      collection: "bullionCrests",
    },
    {
      id: "7",
      name: "Villanova Grey",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/7.jpg",
      collection: "bullionCrests",
    },
    {
      id: "8",
      name: "Villanova Grey Gold",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/8.jpg",
      collection: "bullionCrests",
    },
    {
      id: "9",
      name: "Villanova Red",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/9.jpg",
      collection: "bullionCrests",
    },
    {
      id: "10",
      name: "Villanova Silver",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/10.jpg",
      collection: "bullionCrests",
    },
    {
      id: "11",
      name: "Mountee Gold",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/11.jpg",
      collection: "bullionCrests",
    },
    {
      id: "12",
      name: "Royal Squadron",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/12.jpg",
      collection: "bullionCrests",
    },
    {
      id: "13",
      name: "Regard",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/13.jpg",
      collection: "bullionCrests",
    },
    {
      id: "14",
      name: "Mountee Copper",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/14.jpg",
      collection: "bullionCrests",
    },
    {
      id: "15",
      name: "Arbor",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/15.jpg",
      collection: "machinedBadges",
    },
    {
      id: "16",
      name: "FAI",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/16.jpg",
      collection: "machinedBadges",
    },
    {
      id: "17",
      name: "Royal Crest",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/17.jpg",
      collection: "bullionCrests",
    },
    {
      id: "18",
      name: "Corrections",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/18.jpg",
      collection: "machinedBadges",
    },
    {
      id: "19",
      name: "Waterloo",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/19.jpg",
      collection: "bullionCrests",
    },
    {
      id: "20",
      name: "Royal",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/20.jpg",
      collection: "machinedBadges",
    },
    {
      id: "21",
      name: "Lauren",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/21.jpg",
      collection: "machinedBadges",
    },
    {
      id: "22",
      name: "Wilfrid Laurier",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/22.jpg",
      collection: "machinedBadges",
    },
    {
      id: "23",
      name: "Royal Crest",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/23.jpg",
      collection: "machinedBadges",
    },
    {
      id: "24",
      name: "Toronto Police Blue",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/24.jpg",
      collection: "bullionCrests",
    },
    {
      id: "25",
      name: "Crowns",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/25.jpg",
      collection: "bullionCrests",
    },
    {
      id: "26",
      name: "Bigg's",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/26.jpg",
      collection: "machinedBadges",
    },
    {
      id: "27",
      name: "Canada Leaf",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/27.jpg",
      collection: "bullionCrests",
    },
    {
      id: "28",
      name: "Royal Dolphin",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/28.jpg",
      collection: "bullionCrests",
    },
    {
      id: "29",
      name: "Peninsula",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/29.jpg",
      collection: "bullionCrests",
    },
    {
      id: "30",
      name: "Ag",
      collection: "machinedBadges",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/30.jpg",
    },
    {
      id: "31",
      name: "WAG",
      collection: "bullionCrests",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/31.jpg",
    },
    {
      id: "32",
      name: "Exemplo",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/32.jpg",
      collection: "machinedBadges",
    },
    {
      id: "33",
      name: "Royal",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/33.jpg",
      collection: "bullionCrests",
    },
    {
      id: "34",
      name: "Lauren Ralph",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/34.jpg",
      collection: "bullionCrests",
    },
    {
      id: "35",
      name: "Services Batillion",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/35.jpg",
      collection: "bullionCrests",
    },
    {
      id: "36",
      name: "Police",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/36.jpg",
      collection: "bullionCrests",
    },
    {
      id: "37",
      name: "Lauren",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/37.jpg",
      collection: "bullionCrests",
    },
    {
      id: "38",
      name: "Et Gloria",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/38.jpg",
      collection: "bullionCrests",
    },
    {
      id: "39",
      name: "University Toronto",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/39.jpg",
      collection: "bullionCrests",
    },
    {
      id: "40",
      name: "US Air Force",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/40.jpg",
      collection: "bullionCrests",
    },
    {
      id: "41",
      name: "Halifax Regional",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/41.jpg",
      collection: "bullionCrests",
    },
    {
      id: "42",
      name: "Golden Triangle",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/42.jpg",
      collection: "bullionCrests",
    },
    {
      id: "43",
      name: "SMUS",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/43.jpg",
      collection: "bullionCrests",
    },
    {
      id: "44",
      name: "US Air Force",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/44.jpg",
      collection: "machinedBadges",
    },
    {
      id: "45",
      name: "Eagle Ranch",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/45.jpg",
      collection: "machinedBadges",
    },
    {
      id: "46",
      name: "Warwickshire",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/46.jpg",
      collection: "machinedBadges",
    },
    {
      id: "47",
      name: "Correctional",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/47.jpg",
      collection: "machinedBadges",
    },
    {
      id: "48",
      name: " Transport",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/48.jpg",
      collection: "machinedBadges",
    },
    {
      id: "49",
      name: "OPP",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/49.jpg",
      collection: "machinedBadges",
    },
    {
      id: "50",
      name: "American Flag",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/50.jpg",
      collection: "arras",
    },
    {
      id: "51",
      name: " Canadian Flag",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/51.jpg",
      collection: "arras",
    },
    {
      id: "52",
      name: "Squadron",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/52.jpg",
      collection: "bullionCrests",
    },
    {
      id: "53",
      name: "Golden Aiguillette",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/aiguillette.jpg",
      collection: "aiguillette",
    },   
    {
      id: "54",
      name: "Silver Maple Leaf Braid",
      description:  "Make a statement with our stylish and versatile Badges. Whether you want to showcase your affiliation, promote your brand, or simply add a touch of personal flair, this badge is the perfect accessory.",
      price: 39.99,
      image: "/Canadianbraid.jpg",
      collection: "braiding",
    },

  ];
export const getAllProducts = () => {
    return products;
};
  
export const getProductById = (id: string) => {
    return products.find((product) => product.id === id);
};